"""Stage 12: generate the alpha=1.0 and alpha=0.1 federated client partitions.

Thin Stage 12 wrapper around the FROZEN Stage 9 partition implementation
(:mod:`recsys23_fedrec.federated.partition`) — the same
``dirichlet_partition`` over joint (click, install) label states, the same
``default_rng(seed)`` consumption order, the same manifest builder. Nothing
about the partition mechanism is reimplemented or altered.

What this script does:
* verifies every protected artifact (read-only) before touching anything,
* loads the FROZEN centralized split (3,137,266 train / 348,586 validation),
* streams only the two label columns of the processed train Parquet,
* partitions the TRAIN rows only (validation/test never enter the space),
* writes, for each of alpha in {1.0, 0.1}, seed 42:
    artifacts/federated/partitions/stage12_partition_alpha_<tag>_seed42.npz
    artifacts/federated/partitions/stage12_partition_alpha_<tag>_seed42.json

What this script NEVER does:
* does not regenerate, move, or modify the frozen Stage 9 alpha=0.5
  partition (``artifacts/federated/partition_alpha_0_5_seed42.*``),
* does not touch validation or official test data,
* does not train anything, save checkpoints, or write outside the Stage 12
  partitions directory.

Re-running this script is safe: identical inputs reproduce byte-identical
partition artifacts (PCG64 determinism, largest-remainder integer
correction, fixed joint-state iteration order). Existing files are
re-written only if identical content would be produced — the script
verifies this before overwriting and refuses on any mismatch.

Usage:
    python scripts/run_stage12_partitions.py [--alphas 1.0 0.1] [--seed 42]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
for path in (str(PROJECT_ROOT / "src"), str(PROJECT_ROOT)):
    if path not in sys.path:
        sys.path.insert(0, path)

from recsys23_fedrec.data import FeatureSet  # noqa: E402
from recsys23_fedrec.experiments.integrity import (  # noqa: E402
    PROTECTED_VALUES,
    snapshot_protected_artifacts,
)
from recsys23_fedrec.federated.partition import (  # noqa: E402
    CLIENT_IDS,
    build_manifest,
    dirichlet_partition,
    load_train_labels,
    save_partition_arrays,
    train_labels_hash,
)
from recsys23_fedrec.federated.stage12_matrix import (  # noqa: E402
    MATRIX_ALPHAS,
    PARTITION_SEED,
    STAGE12_PARTITIONS_DIR,
    get_partition_paths,
    partition_name,
)
from recsys23_fedrec.training.split import load_split  # noqa: E402

TOTAL_TRAIN_ROWS = 3_137_266
TOTAL_DATASET_ROWS = 3_485_852


def _generate_one(alpha: float, seed: int, split, labels, labels_hash: str) -> dict:
    """Generate + persist one Stage 12 partition; return its manifest."""
    project_root = PROJECT_ROOT
    npz_relpath, manifest_relpath = get_partition_paths(alpha)
    npz_path = project_root / npz_relpath
    manifest_path = project_root / manifest_relpath
    print(f"\n--- partition alpha={alpha} seed={seed} ---", flush=True)

    client_indices = dirichlet_partition(labels, alpha=alpha, seed=seed)

    manifest = build_manifest(
        client_indices,
        labels,
        alpha=alpha,
        seed=seed,
        source_split_path="artifacts/splits/centralized_split.json",
        source_split_train_index_hash=split.train_index_hash,
        labels_hash=labels_hash,
        notes=(
            "Stage 12 matrix partition (alpha-severity level); generated by "
            "scripts/run_stage12_partitions.py with the UNCHANGED Stage 9 "
            "partition implementation (dirichlet_joint_label_proportional_v1) "
            "and the frozen seed-42 PCG64 conventions"
        ),
    )

    # ---- hard invariants before writing anything --------------------------
    sizes = [len(rows) for rows in client_indices]
    assert sum(sizes) == TOTAL_TRAIN_ROWS, "row conservation violated"
    for path in (npz_path, manifest_path):
        if path.exists() and "stage12_partition" not in path.name:
            raise SystemExit(f"refusing to overwrite non-Stage-12 file: {path}")

    # ---- reproducibility guard on re-runs ----------------------------------
    if manifest_path.exists():
        existing = json.loads(manifest_path.read_text(encoding="utf-8"))
        comparable = {k: v for k, v in existing.items() if k not in ("notes",)}
        new_comparable = {k: v for k, v in manifest.items() if k not in ("notes",)}
        if json.dumps(comparable, sort_keys=True) != json.dumps(new_comparable, sort_keys=True):
            raise SystemExit(
                f"{manifest_relpath} exists with DIFFERENT content; Stage 12 "
                "partitions must be reproducible — aborting instead of overwriting."
            )
        print(f"  {manifest_relpath}: already exists and is byte-consistent (re-run OK)",
              flush=True)
    else:
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
        print(f"  manifest written: {manifest_relpath}", flush=True)

    if not npz_path.exists():
        save_partition_arrays(client_indices, npz_path, partition_hash_value=manifest["partition_hash"])
        print(f"  index arrays written: {npz_relpath}", flush=True)
    else:
        print(f"  index arrays already present: {npz_relpath} (re-run OK)", flush=True)

    # ---- summary -----------------------------------------------------------
    g = manifest["global_label_distribution"]
    print(f"  partition hash: {manifest['partition_hash']}", flush=True)
    print(f"  global: click {g['click_rate']:.4f} | install {g['install_rate']:.4f}", flush=True)
    print("  client |    rows |   %    | click | install", flush=True)
    for c, cid in enumerate(CLIENT_IDS):
        s = manifest["clients"][cid]
        print(
            f"  {cid} | {s['rows']:>7,} | {s['row_percentage']:>5.2f}% | "
            f"{s['click_rate']:.4f} | {s['install_rate']:.4f}",
            flush=True,
        )
    sizes_min, sizes_max = min(sizes), max(sizes)
    print(f"  sizes: min {sizes_min:,} / max {sizes_max:,} (max/min = {sizes_max / sizes_min:.2f})",
          flush=True)
    het = manifest["heterogeneity"]
    print(
        f"  heterogeneity: mean |delta joint proportion| = "
        f"{het['mean_absolute_joint_proportion_deviation']:.4f}, max = "
        f"{het['max_absolute_joint_proportion_deviation']:.4f}",
        flush=True,
    )
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--alphas", type=float, nargs="+", default=[1.0, 0.1],
                        choices=sorted(a for a in MATRIX_ALPHAS if a != 0.5),
                        help="Stage 12 alphas to generate (0.5 stays frozen in Stage 9)")
    parser.add_argument("--seed", type=int, default=PARTITION_SEED)
    args = parser.parse_args()

    print("=== Stage 12: alpha=1.0 / alpha=0.1 federated client partitions ===", flush=True)

    # ---- integrity gate: frozen artifacts must be intact -------------------
    print("\n--- protected artifact integrity (read-only) ---", flush=True)
    snapshot = snapshot_protected_artifacts(PROJECT_ROOT)
    for key, expected in PROTECTED_VALUES.items():
        actual = snapshot[key]
        status = "OK" if actual == expected else "MISMATCH"
        print(f"  {key}: {actual} (expected {expected}) [{status}]", flush=True)
        if actual != expected:
            print("FATAL: protected artifact integrity violated; aborting.", flush=True)
            return 1
    print("  all protected artifacts intact", flush=True)

    # ---- frozen split verification -----------------------------------------
    print("\n--- frozen split verification ---", flush=True)
    split = load_split(
        PROJECT_ROOT / "artifacts" / "splits" / "centralized_split.json",
        expected_total_rows=TOTAL_DATASET_ROWS,
    )
    print(f"  train rows: {split.train_rows:,} (hash {split.train_index_hash})", flush=True)
    print(f"  validation rows: {len(split.validation_indices):,} "
          f"(hash {split.validation_index_hash}) — stays globally held out", flush=True)
    if split.train_rows != TOTAL_TRAIN_ROWS:
        print(f"FATAL: expected {TOTAL_TRAIN_ROWS:,} train rows.", flush=True)
        return 1

    # ---- labels (train space only) ------------------------------------------
    print("\n--- streaming train labels (is_clicked, is_installed) ---", flush=True)
    train_dir = PROJECT_ROOT / "artifacts" / "processed" / "train"
    all_labels = load_train_labels(train_dir, expected_total_rows=TOTAL_DATASET_ROWS)
    print(f"  processed rows read: {len(all_labels):,} (train+validation space)", flush=True)
    feature_set = FeatureSet.load(PROJECT_ROOT / "artifacts" / "preprocessing")
    print(f"  Stage 2 artifact hash: {feature_set.artifact_hash}", flush=True)
    labels = all_labels[split.train_indices]
    if len(labels) != TOTAL_TRAIN_ROWS:
        print(f"FATAL: train label rows {len(labels):,} != {TOTAL_TRAIN_ROWS:,}", flush=True)
        return 1
    print(f"  train-only labels after split subsetting: {len(labels):,}", flush=True)
    print("  validation rows (348,586) excluded from the partition space", flush=True)
    labels_hash = train_labels_hash(labels)
    print(f"  train-labels hash: {labels_hash}", flush=True)

    # ---- generate both partitions -------------------------------------------
    manifests = {
        alpha: _generate_one(alpha, args.seed, split, labels, labels_hash)
        for alpha in args.alphas
    }

    print("\n--- Stage 12 partition cross-checks ---", flush=True)
    for alpha, manifest in manifests.items():
        sizes = manifest["rows_per_client"]
        total = sum(sizes)
        ok_total = total == TOTAL_TRAIN_ROWS
        print(f"  alpha={alpha}: 10 clients, rows sum {total:,} "
              f"{'OK' if ok_total else 'FATAL'}, partition hash {manifest['partition_hash']}",
              flush=True)
        if not ok_total:
            return 1
    print("\n  no validation/test rows used; no training performed; the Stage 9 "
          "alpha=0.5 partition was not touched.", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
